version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: .
    volumes:
      - .:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - postgres_data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: {}